### ISSUE TITLE
Propongo que Yareth haga algo útil

### ISSUE THREAD

**Issue by WilmanOnRails** [iDarkGG/ProyectoFinal#1]
Sino valemos riata

**Comment by iDarkGG** [comment]
Jsjs

**Comment by WilmanOnRails** [comment]
Aqui esperando a que Yareth haga algo

![Captura de pantalla 2022-10-05 085423](https://user-images.githubusercontent.com/104475915/194092168-5d99446e-6c65-4b9e-8352-8bcd122eef1f.png)
